#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : commonmark
Version  : 0.9.1
Release  : 15
URL      : https://files.pythonhosted.org/packages/60/48/a60f593447e8f0894ebb7f6e6c1f25dafc5e89c5879fdc9360ae93ff83f0/commonmark-0.9.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/60/48/a60f593447e8f0894ebb7f6e6c1f25dafc5e89c5879fdc9360ae93ff83f0/commonmark-0.9.1.tar.gz
Summary  : Python parser for the CommonMark Markdown spec
Group    : Development/Tools
License  : BSD-3-Clause
Requires: commonmark-bin = %{version}-%{release}
Requires: commonmark-license = %{version}-%{release}
Requires: commonmark-python = %{version}-%{release}
Requires: commonmark-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
=============

%package bin
Summary: bin components for the commonmark package.
Group: Binaries
Requires: commonmark-license = %{version}-%{release}

%description bin
bin components for the commonmark package.


%package license
Summary: license components for the commonmark package.
Group: Default

%description license
license components for the commonmark package.


%package python
Summary: python components for the commonmark package.
Group: Default
Requires: commonmark-python3 = %{version}-%{release}

%description python
python components for the commonmark package.


%package python3
Summary: python3 components for the commonmark package.
Group: Default
Requires: python3-core
Provides: pypi(commonmark)

%description python3
python3 components for the commonmark package.


%prep
%setup -q -n commonmark-0.9.1
cd %{_builddir}/commonmark-0.9.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1603388606
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/commonmark
cp %{_builddir}/commonmark-0.9.1/LICENSE %{buildroot}/usr/share/package-licenses/commonmark/7df36cd9b2fdbd800a7fa19b3faad20561a7e917
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cmark

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/commonmark/7df36cd9b2fdbd800a7fa19b3faad20561a7e917

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
